name: ioncoin
version: v3.1.00
summary:   peer-to-peer network based digital currency
description: |
  ION is an MIT licensed,
  open source, blockchain-based cryptocurrency with 
  ultra fast transactions, low fees, high network decentralization, and
  Zero Knowledge cryptography proofs for industry-leading
  transaction anonymity. 
  
  Wiki (Ionomy):   https://github.com/ionomy/ion/wiki
  Wiki (IonomyCE): https://github.com/cevap/ion/wiki
  
  Technical documentaion: https://techdoc.ioncore.xyz
  
  Whitepaper: https://ionomy.com/en/whitepaper
  
  Technical whitepaper: 
    https://github.com/ionomy/ion/wiki/ION-Technical-Whitepaper
  
  Get source code from Github: https://github.com/ioncoincore/ion.git
  
  Chat with Support on Discord: https://discord.gg/vuZn7gC
  
  Contact us on social networks and forums
    Instagram: https://t.me/ionomy
    Twitter:   https://twitter.com/ionomics
    Reddit:    https://www.reddit.com/r/ionomy/
    Facebook:  https://facebook.com/ionomy

grade: stable
confinement: strict

apps:
  daemon:
    command: iond
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt:
    command: desktop-launch ion-qt
    plugs: [network, network-bind, unity7, desktop, desktop-legacy, wayland, x11]
    desktop: ion.desktop
  cli:
    command: ion-cli
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  tx:
    command: ion-tx

parts:
  ion:
    source: https://github.com/cevap/ion
    source-type: git
    source-tag: v3.1.00
    plugin: autotools
    # We don't want to copy the full blockchain every time that the snap is   
    # updated, but there's no way to define a default data dir in bitcoin-qt.
    # Also, it would be better if we could split the wallet from the blockchain
    prepare: git apply $SNAPCRAFT_STAGE/default_data_dir.patch
    build-packages:
      - g++
      - autoconf
      - automake
      - pkg-config
      - libssl-dev
      - libevent-dev
      - bsdmainutils
      - libgmp-dev
      # Boost.
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-thread-dev
      # Optional.
      - libminiupnpc-dev
      - libzmq3-dev
      # GUI.
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      # Optional.
      - libqrencode-dev
    stage-packages: [ca-certificates]
    after:
      - berkeleydb
      - desktop-qt5
      - patches
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
    plugin: nil
    build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
    install: |
      cd build_unix
      make install
    prime:
      - -*
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/gui
    plugin: dump
